# Use OpenJDK 17 as base
#FROM openjdk:17-jdk-slim
FROM eclipse-temurin:17-jdk
#FROM openjdk:21-jdk-slim

# Set working directory
WORKDIR /app

# Copy the built jar file
COPY target/*.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the Spring Boot app
ENTRYPOINT ["java","-jar","app.jar"]
